# Generated by Django 5.2.13 on 2026-04-25 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='ForgeCMS', max_length=160)),
                ('tagline', models.CharField(blank=True, default='CMS modulaire prêt pour devenir une CMS Factory', max_length=220)),
                ('default_theme', models.CharField(default='default', max_length=120)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètre du site',
                'verbose_name_plural': 'Paramètres du site',
            },
        ),
    ]
